fallback-grpc-addr: 127.0.0.1:3030
dial-grpc-timeout: 10

jaeger:
  url: "http://127.0.0.1:14268/api/traces"

consul:
  addr: 127.0.0.1:8500


order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8283
  grpc-addr: 127.0.0.1:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8284
  grpc-addr: 127.0.0.1:5004

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672

stripe-key: sk_test_51RHe60PvlGOuxYfJYBmKuCNuoaGIeztsqdGAexh6af6VVz7qbuWjFvCadNTTnhCUi57UEWBP9DWia4DwS6h5pmlJ00OIHzfm9x
endpoint-stripe-secret: whsec_42ab5b7e5743c11bb42dba658b77550c07d61fb529d38f58fc1600c1cd1859d1